version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REGION="eu-central-1"
      - VERSION=development
      - ECR="xxxxxxxxxxxx.dkr.ecr.eu-central-1.amazonaws.com"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images ...
      - docker-compose build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker-compose push
